.TH arc-unpacker 8  "April 23, 2012" "version ${maven.deb.version}" "USER COMMANDS"
.SH NAME
arc-unpack \- ${maven.deb.description}
.SH SYNOPSIS
.B arc-unpack
\-f dataFile [\-o outputDir] [\-minResp number] [\-maxResp number] [\-naming [MD5,OFFSET,URL]]
.SH DESCRIPTION
${maven.deb.extendedDescription}
.SH OPTIONS
.TP
\-f dataFile
Data file to extract. Can be an arc or warc file, and can be compressed.
.TP
\-o outputDir
extracts the resources to this dir. Defaults to the current dir.
.TP
\-minResp number
Ignore resources, if the http return code is lower than minResp. Useful to filter out returns below the 200 range
.TP
\-maxResp number
Ignore resources, if the http return code is higher than maxResp. Useful to filter out returns above the 200 range
.TP
\-naming [MD5,OFFSET,URL]
Naming scheme for the extracted resources. Each resource in the archive is identified by an URL, but URLs do not map
neatly to filenames.
The URL scheme tries to map the resource urls to files, but can fail.
The OFFSET scheme uses offsets into the arc file as filenames
The MD5 scheme md5hash the resource URLs to ensure valid unique filenames
.SH EXIT STATUS
arc-unpack returns zero if the extraction succeeded
.SH AUTHOR
${maven.deb.maintainer}
